"""Opt-in per-task physical memory ceiling: ``@task(memory_limit_mb=...)``.

Runs the task's function in an isolated subprocess and polls its
resident memory (RSS) via a high-frequency watchdog; the instant it
crosses the limit, the subprocess is ``SIGKILL``ed and the outcome is a
``MemoryLimitExceeded`` -- a recorded result (``status="oom"`` in the
state file), not an uncaught crash or a silently OS-OOM-killed process.

Why a watchdog instead of ``resource.RLIMIT_AS``: ``RLIMIT_AS`` caps
virtual address space, which multi-threaded, arena-allocating engines
(Polars, DuckDB, Daft) reserve far in excess of the RAM they actually
commit -- so it fires on reservation strategy, not memory pressure.
Polling RSS and killing on breach measures and enforces real memory,
works identically on macOS and Linux, and turns OOM into a recorded
result. This is not a new idea invented for DuckPipe: it generalizes a
pattern proven in production dogfooding -- a real multi-engine
benchmark harness that runs the same task under a physical cap and
records the OOM as a first-class outcome instead of a crash.

Needs ``cloudpickle`` (to serialize a task function that may be a
closure -- e.g. one generated by the fan-out pattern, not just a plain
module-level function) and ``psutil`` -- both lazy imports, listed
under the `duckpipe[memcap]` extra so the core dependency tree stays
untouched for anyone not using this. The same picklability limits
`cache=True`'s pickle backend already documents apply here too: a task
whose upstream inputs are a live, unpicklable handle (a `DuckDBPyRelation`,
say) can't cross the subprocess boundary either.

One sharp edge found the hard way while testing this: cloudpickle
prefers to pickle a function *by reference* (re-import by its module's
dotted name) whenever that module looks like a normal, importable one --
and gets this wrong specifically for a function defined directly in a
Jupyter notebook cell or a pytest test module, since neither is
reliably re-importable from a fresh subprocess's own `sys.path`, even
though cloudpickle can't tell that from the outside. A task defined in
an actual pipeline file (standalone script or real package module, the
normal case) doesn't have this problem. If a memory-capped task defined
directly in a notebook cell fails with a `ModuleNotFoundError` for a
module that clearly exists, move it into its own `.py` file.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import psutil

_BYTES_PER_MB = 1024 * 1024


class MemoryLimitExceeded(RuntimeError):
    """Raised when a memory-capped task's subprocess crosses its
    ``memory_limit_mb`` -- caught by the scheduler and recorded as
    ``status="oom"`` rather than ``"failed"``."""

    def __init__(self, task_name: str, limit_mb: int, peak_mb: float) -> None:
        self.task_name = task_name
        self.limit_mb = limit_mb
        self.peak_mb = peak_mb
        super().__init__(
            f"task {task_name!r} exceeded its {limit_mb}MB memory_limit_mb "
            f"(peak observed: {peak_mb:.1f}MB)"
        )


def run_capped(
    task_name: str,
    func: Callable[..., Any],
    kwargs: dict[str, Any],
    *,
    limit_mb: int,
    poll: float = 0.005,
) -> Any:
    try:
        import cloudpickle
        import psutil
    except ImportError as exc:
        raise ImportError(
            "memory_limit_mb needs the optional 'memcap' extra: "
            'uv add "duckpipe[memcap]" (adds cloudpickle + psutil)'
        ) from exc

    with tempfile.TemporaryDirectory(prefix="duckpipe_memcap_") as td:
        payload_path = os.path.join(td, "payload.pkl")
        result_path = os.path.join(td, "result.pkl")
        with open(payload_path, "wb") as f:
            cloudpickle.dump({"func": func, "kwargs": kwargs}, f)

        proc = subprocess.Popen(
            [sys.executable, "-m", "duckpipe._memcap_worker", payload_path, result_path],
            stderr=subprocess.PIPE,
        )
        ps = psutil.Process(proc.pid)
        limit_bytes = limit_mb * _BYTES_PER_MB
        peak = 0

        while proc.poll() is None:
            try:
                rss = _tree_rss(ps)
            except psutil.NoSuchProcess:
                break
            peak = max(peak, rss)
            if rss > limit_bytes:
                _kill_tree(ps)
                raise MemoryLimitExceeded(task_name, limit_mb, peak / _BYTES_PER_MB)
            time.sleep(poll)

        stderr = proc.stderr.read().decode(errors="replace") if proc.stderr else ""
        proc.wait()

        if not os.path.exists(result_path):
            # Killed by the OS's own OOM killer (the watchdog above never
            # saw the breach in time), or crashed before writing at all.
            raise RuntimeError(
                f"task {task_name!r} subprocess exited (code {proc.returncode}) with no "
                f"result: {stderr.strip()[-2000:] or '(no stderr)'}"
            )

        with open(result_path, "rb") as f:
            result = cloudpickle.load(f)

    if result["status"] == "error":
        raise RuntimeError(result["error"])
    return result["value"]


def _tree_rss(ps: psutil.Process) -> int:
    """Total RSS of the worker and any children it spawns."""
    import psutil

    total = ps.memory_info().rss
    for child in ps.children(recursive=True):
        try:
            total += child.memory_info().rss
        except psutil.NoSuchProcess:
            pass
    return total


def _kill_tree(ps: psutil.Process) -> None:
    import psutil

    procs = ps.children(recursive=True) + [ps]
    for p in procs:
        try:
            p.kill()
        except psutil.NoSuchProcess:
            pass
    psutil.wait_procs(procs, timeout=3)
